import type { Metadata } from 'next';
import type { ReactNode } from 'react';

import { GeistSans } from 'geist/font/sans';

import '$/styles/globals.css';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html className={`${GeistSans.variable} antialiased`} lang='en' suppressHydrationWarning>
      <body className='font-display'>{children}</body>
    </html>
  );
}
